MONDO_AUTH_URL = 'https://staging-auth.getmondo.co.uk'
MONDO_API_URL = 'https://staging-api.getmondo.co.uk'
MONDO_CLIENT_ID = 'oauthclient_000094RmbmkvjhMwyzx0Gf'
MONDO_CLIENT_SECRET = 'aZ/XRhXQrAhAbzuHUIQi3HIoDi8mlKxa9htThSi0vGKChNS3WFLwQC7AdvHtFO6tgGTGY3VaTsfecD2hG+tE'
MONDO_REDIRECT_URL = 'http://localhost:8000/mondo/authorize/'
